CONTAINER_NAME=cliente

is_running = $(shell docker ps --filter "name=$(1)" --filter "status=running" -q)

is_stopped = $(shell docker ps -a --filter "name=$(1)" --filter "status=exited" -q)

start_contenedor:
	@if [ -z "$(call is_running,$(CONTAINER_NAME))" ]; then \
		if [ -n "$(call is_stopped,$(CONTAINER_NAME))" ]; then \
			echo "Iniciando el contenedor Cliente..."; \
			docker start $(CONTAINER_NAME); \
		else \
			echo "Cliente ya esta corriendo o no existe."; \
		fi \
	else \
		echo "Cliente ya esta corriendo."; \
	fi

docker-clientes: start_contenedor
	@echo "Cliente se han iniciado si estaban apagados."
